Adicionado UsuarioRepository
g-asantos/trabgerconfigsoftware pull request #6
Opened 2022-10-02 17:57 UTC by franciscoftarga

Adicionado Classe UsuarioRepository com os seguintes métodos:

- Criar
- Listar
- Listar por Tipo
- Listar Médico ou Paciente

Criados a partir do diagrama.

2022-10-02 18:34 UTC, fcfrison requested changes

2022-10-02 18:34 UTC, fcfrison commented on src/repository/UsuarioRepository.java
> +
Deve ser inserido um atributo estático do tipo:
`private static int id;`
Esse atributo garante a consistência na criação de identificadores, garantindo, por exemplo, que eles sejam únicos.

2022-10-02 18:34 UTC, fcfrison commented on src/repository/UsuarioRepository.java
> +    public Usuario Criar(int id, String nome, TipoUsuario tipoUsuario) {
É necessário retirar o parâmetro `int id` da assinatura do método. Ou seja, 
`public Usuario Criar(String nome, TipoUsuario tipoUsuario)`. Além disso, 
deve ser buscado o valor do 'id' a partir do atributo estático criado acima. 
Ou seja, fazer algo do tipo:
```
Usuario usuario = new Usuario(id, nome, tipoUsuario);
id++;

```

2022-10-02 18:34 UTC, fcfrison commented on src/repository/UsuarioRepository.java
> +public class UsuarioRepository {
Você deve encapsular o construtor da classe para garantir que o padrão _Singleton_ seja seguido. Minha sugestão é:
```
private static UsuarioRepository instance;
private UsuarioRepository (){};
public static UsuarioRepository getInstance(){
        if(instance == null){
            instance = new UsuarioRepository ();
        }

        return instance;
    }
```
Caso o meu comentário não tenha sido claro o bastante, sugiro que você dê uma olhada nos outros _repositories_.

2022-10-03 12:24 UTC, fcfrison approved these changes
O código está correto. Ainda não é possível uma completa validação dos métodos. Porém, eles parecem ter sido corretamente implementados.

2022-10-03 12:33 UTC, alexiadorneles requested changes

2022-10-03 12:33 UTC, alexiadorneles commented on src/repository/UsuarioRepository.java
> +    public Usuario Criar(String nome, TipoUsuario tipoUsuario) {
Métodos em java sao camelCase, entao aqui seria `criar`, minúsculo

2022-10-03 12:33 UTC, alexiadorneles commented on src/repository/UsuarioRepository.java
> +            if (usuario.getNome() == nome && usuario.getTipo() == TipoUsuario.PACIENTE || usuario.getTipo() == TipoUsuario.MEDICO) {
Ao invés de == aqui seria melhor usar um `contains` assim procuramos em qualquer lugar da string ao invés de igualdade. Exemplo: se tivermos os nomes Ana e Joana, ao procurar por "ana" vai retornar os dois se usarmos contains.

2022-10-03 12:33 UTC, alexiadorneles commented on src/repository/UsuarioRepository.java
> +    public int proxId(){
Esse método nao é necessario. Na hora de passar o id voce pode só dar um `++UsuarioRepository.id`

2022-10-03 20:23 UTC, alexiadorneles approved these changes

2022-10-03 20:24 UTC, merged